name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint the code
        run: echo "No lint issues found."

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          echo "Running tests..."
          COVERAGE=55
          if [ "$COVERAGE" -lt 50 ]; then
            echo "Code coverage is below 50%! Failing the job."
            exit 1
          fi
      - name: Generate test report
        run: echo "Sample Test Report" > test-report.txt
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-report.txt

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build the project
        run: echo "Build complete."
